DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): 2d58-77-45-151-104.ngrok-free.app:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://2d58-77-45-151-104.ngrok-free.app:443 "POST /api/create HTTP/11" 200 2
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): 2d58-77-45-151-104.ngrok-free.app:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://2d58-77-45-151-104.ngrok-free.app:443 "GET /api/get/14 HTTP/11" 200 164
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): 2d58-77-45-151-104.ngrok-free.app:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://2d58-77-45-151-104.ngrok-free.app:443 "DELETE /api/delete/14 HTTP/11" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): 2d58-77-45-151-104.ngrok-free.app:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://2d58-77-45-151-104.ngrok-free.app:443 "GET /api/get/14 HTTP/11" 500 33
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): 2d58-77-45-151-104.ngrok-free.app:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://2d58-77-45-151-104.ngrok-free.app:443 "GET /api/getall/ HTTP/11" 200 13
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): 2d58-77-45-151-104.ngrok-free.app:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://2d58-77-45-151-104.ngrok-free.app:443 "DELETE /api/delete/14 HTTP/11" 500 37
ERROR    root:conftest.py:32 Failed to delete entity 14: 500 Server Error: Internal Server Error for url: https://2d58-77-45-151-104.ngrok-free.app/api/delete/14
Traceback (most recent call last):
  File "/home/runner/work/TestNest/TestNest/tests/api/conftest.py", line 29, in new_entity
    entity_service.delete_entity(str(entity.id))
  File "/home/runner/work/TestNest/TestNest/services/entity/entity_service.py", line 60, in delete_entity
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://2d58-77-45-151-104.ngrok-free.app/api/delete/14